version: '2.4'

services:
  app:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
    shm_size: '30gb'
    environment:
      - STORE_URL
    volumes:
      - ./:/srv
      - ./store:/store
      - ./.cache:/root/.cache
      - ./signate.json:/root/.signate/signate.json
    runtime: nvidia
